package net.atos.entng.wiki.broker;

import io.vertx.core.Future;
import org.entcore.broker.api.BrokerPublisher;


public interface AIWikiGeneratorPublisher {
    //TODO should be generated by cli
    @BrokerPublisher(subject = "ai.wiki.create")
    Future<Void> createWiki(ContentRequest var1);
}
