package net.atos.entng.wiki.broker;

import io.vertx.core.Future;
import org.entcore.broker.api.BrokerListener;
import org.entcore.edificewikigenerator.CourseResponse;

public interface AIWikiGeneratorListener {
    //TODO should be generated by cli

    @BrokerListener(
            subject = "ia.wiki.content.updated",
            proxy = true
    )
    Future<Void> updateWikiContent(CourseResponse content);

    @BrokerListener(
            subject = "ia.wiki.structure.updated",
            proxy = true
    )
    Future<Void>  updateWikiStructure(CourseHierarchy structure);
}
