package net.atos.entng.wiki.broker;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Request payload for AI wiki generation.
 * This class represents the data sent to the AI service to generate wiki content.
 */
public class ContentRequest {
    //TODO should be generated by cli
    private final String userId;
    private final String wikiId;
    private final String session;
    private final String browser;
    private final String level;
    private final String subject;
    private final String content;
    private final String keywords;

    @JsonCreator
    public ContentRequest(
            @JsonProperty("user_id") String userId,
            @JsonProperty("wiki_id") String wikiId,
            @JsonProperty("session") String session,
            @JsonProperty("browser") String browser,
            @JsonProperty("level") String level,
            @JsonProperty("subject") String subject,
            @JsonProperty("content") String content,
            @JsonProperty("keywords") String keywords) {
        this.userId = userId;
        this.wikiId = wikiId;
        this.session = session;
        this.browser = browser;
        this.level = level;
        this.subject = subject;
        this.content = content;
        this.keywords = keywords;
    }

    @JsonGetter("user_id")
    public String getUserId() {
        return userId;
    }

    @JsonGetter("wiki_id")
    public String getWikiId() {
        return wikiId;
    }

    @JsonGetter("session")
    public String getSession() {
        return session;
    }

    @JsonGetter("browser")
    public String getBrowser() {
        return browser;
    }

    @JsonGetter("level")
    public String getLevel() {
        return level;
    }

    @JsonGetter("subject")
    public String getSubject() {
        return subject;
    }

    @JsonGetter("content")
    public String getContent() {
        return content;
    }

    @JsonGetter("keywords")
    public String getKeywords() {
        return keywords;
    }
}