package net.atos.entng.wiki.broker;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.entcore.edificewikigenerator.PageStructure;

import java.util.List;
//TODO should be generated by cli
public class CourseHierarchy {
    private final String _id;
    private final List<PageStructure> pages;

    @JsonCreator
    public CourseHierarchy(@JsonProperty("_id") String _id, @JsonProperty("pages") List<PageStructure> pages) {
        this._id = _id;
        this.pages = pages;
    }

    @JsonGetter("_id")
    public String getId() {
        return this._id;
    }

    @JsonGetter("pages")
    public List<PageStructure> getPages() {
        return this.pages;
    }
}
