export const usePagesAssistantAI = () => {
  const levelsData = [
    {
      value: '5ème',
      subjects: [
        {
          value: 'Technologie',
          sequences: [
            "De l'analyse du besoin aux fonctions de l'objet",
            'Imaginer et représenter des solutions techniques en équipe',
            '[SYNTHÈSE] Créer un objet unique : le porte-clé personnalisé et écologique',
            "Anatomie d'un objet simple : comment ça marche ?",
            "L'évolution des objets et leur impact sur nos vies",
            'Identifier et choisir les matériaux',
            "Analyser la structure et les mécanismes d'un objet",
            'Atelier de Fabrication : des outils et des règles pour créer',
            'Communiquer une idée : la représentation technique',
            'Concevoir en 3D sur ordinateur (Initiation CAO)',
            "[SYNTHÈSE] Concevoir le boîtier d'un tableau de bord météo",
            'Maîtriser son environnement numérique (ENT)',
            'Premiers pas de Citoyen Numérique : se présenter et échanger en ligne',
            "Donner des ordres à l'ordinateur : l'algorithme et les blocs",
            '[SYNTHÈSE] Automatiser un distributeur de croquettes',
          ],
        },
        {
          value: 'Mathématiques',
          sequences: [
            'Opérations sur les nombres entiers et décimaux',
            'Les fractions : découverte et simplification',
            'Opérations sur les fractions',
            'Nombres relatifs : introduction',
            'La proportionnalité',
            'Statistiques : lire et interpréter',
            'Aires et périmètres',
            'Volumes et conversions',
            'Angles et parallélisme',
            'Les triangles',
            'La symétrie',
          ],
        },
        {
          value: 'Histoire',
          sequences: [
            "Byzance et l'Europe carolingienne",
            "L'Islam : débuts, expansion, sociétés",
            'La Méditerranée : un carrefour de civilisations',
            "L'ordre seigneurial : la formation et la domination des campagnes",
            "L'émergence d'une nouvelle société urbaine",
            "L'affirmation de l'État monarchique en France",
            "Le rôle de l'Église dans la société",
            'Le monde au temps de Charles Quint et Soliman le Magnifique',
            'Humanisme, Réformes et conflits religieux',
            'Du Prince de la Renaissance au roi absolu',
          ],
        },
      ],
    },
    {
      value: '4ème',
      subjects: [
        {
          value: 'Technologie',
          sequences: [
            'Le Cahier des Charges Fonctionnel (CdCF)',
            "Ergonomie et Design : l'expérience utilisateur (UX)",
            'Les Tendances du Design : pourquoi les objets ont ce look ?',
            "[SYNTHÈSE] Améliorer le confort et la sécurité d'un vélo de ville",
            "Analyse de système : Chaîne d'information et d'énergie",
            '[SYNTHÈSE] Piloter une serre de jardin intelligente',
            "Gestion de l'Énergie : comment alimenter nos objets ?",
            'Impact environnemental et Analyse du Cycle de Vie (ACV)',
            "Modélisation 3D d'un mécanisme assemblé (CAO)",
            'La simulation numérique : tester avant de construire',
            'Algorithmique : variables, conditions et boucles',
            'Enquête sur nos Données Numériques : collecte, tri et analyse',
            'Piloter un système : Capteurs, actionneurs et microcontrôleur',
            'Architecture et fonctionnement des réseaux informatiques',
            '[SYNTHÈSE] Mettre en place le réseau pour un tournoi de E-Sport',
          ],
        },
        {
          value: 'Mathématiques',
          sequences: [
            'Opérations avec les nombres relatifs',
            'Le calcul littéral',
            'Les puissances',
            'Statistiques : moyenne et médiane',
            'Introduction aux probabilités',
            'Le théorème de Pythagore',
            'Le cosinus',
            'Le théorème de Thalès',
            'Les triangles semblables',
            'Pyramides et cônes',
            'Algorithmique : variables et boucles',
          ],
        },
        {
          value: 'Histoire',
          sequences: [
            'Bourgeoisies marchandes, négoces internationaux et traite négrière',
            "L'Europe des Lumières",
            "La Révolution française et l'Empire",
            "L'Europe de la 'Révolution industrielle'",
            'Conquêtes et sociétés coloniales',
            'Une difficile conquête : voter de 1815 à 1870',
            'La Troisième République',
            'Conditions féminines dans une société en mutation',
          ],
        },
      ],
    },
    {
      value: '3ème',
      subjects: [
        {
          value: 'Technologie',
          sequences: [
            'Conduire une démarche de projet en équipe',
            'Innover : Veille technologique et propriété intellectuelle',
            '[SYNTHÈSE] Concevoir une lampe intelligente, de son design à son recyclage',
            'Analyse de systèmes complexes et mécatroniques',
            'Du prototype à la série : Procédés de fabrication',
            "Éco-conception et modèle économique : le vrai coût d'un produit",
            'Optimisation et fabrication par impression 3D (FDM)',
            'La Simulation Comportementale : prédire pour mieux concevoir',
            'Du bloc au texte : Initiation à la programmation en Python',
            '[SYNTHÈSE] Sécuriser un portail automatisé et son application',
            'Architecture des Services en Ligne : comment fonctionne une app ?',
            "Projet : Prototyper une solution avec l'Intelligence Artificielle",
            'Cybersécurité : se protéger et protéger ses données',
            "Préparer et présenter son projet pour l'oral du DNB",
            '[PROJET DNB] Planifier et programmer une mission de drone autonome',
          ],
        },
        {
          value: 'Mathématiques',
          sequences: [
            'Nombres premiers et décomposition',
            'Les équations et inéquations',
            "Les systèmes d'équations",
            'Notion de fonction',
            'Fonctions linéaires et affines',
            'Probabilités : événements',
            'La trigonométrie',
            'Agrandissement et réduction',
            'Sphères et boules',
            'Algorithmique avancée',
            'Sujets de Brevet : méthodologie',
          ],
        },
        {
          value: 'Histoire',
          sequences: [
            'Civils et militaires dans la Première Guerre mondiale',
            'Démocraties fragilisées et expériences totalitaires',
            "La Seconde Guerre mondiale, une guerre d'anéantissement",
            'Indépendances et construction de nouveaux États',
            'Un monde bipolaire au temps de la guerre froide',
            'Affirmation et mise en œuvre du projet européen',
            'Enjeux et conflits dans le monde après 1989',
            'La IVe République, une république nouvelle',
            'La Ve République',
            'Femmes et hommes dans la société des années 1950 aux années 1980',
          ],
        },
      ],
    },
  ];

  return {
    levelsData,
  };
};
