import allemandIcon from '../icons/subjects/allemand.png';
import anglaisIcon from '../icons/subjects/anglais.png';
import artsPlastiquesIcon from '../icons/subjects/arts_plastiques.png';
import biologieEcologieIcon from '../icons/subjects/biologie_ecologie.png';
import educationMoraleCiviqueIcon from '../icons/subjects/education_morale_civique.png';
import enseignementScientifiqueIcon from '../icons/subjects/enseignement_scientifique.png';
import epsIcon from '../icons/subjects/eps.png';
import espagnolIcon from '../icons/subjects/espagnol.png';
import francaisIcon from '../icons/subjects/francais.png';
import genericSubjectIcon from '../icons/subjects/genericSubject.png';
import histoireGeoPolitiqueIcon from '../icons/subjects/histoire_geo_politique.png';
import histoireIcon from '../icons/subjects/histoire.png';
import humanitesIcon from '../icons/subjects/humanites.png';
import italienIcon from '../icons/subjects/italien.png';
import llcaIcon from '../icons/subjects/llca.png';
import mathematiquesIcon from '../icons/subjects/mathematiques.png';
import nsiIcon from '../icons/subjects/nsi.png';
import physiqueChimieIcon from '../icons/subjects/physique_chimie.png';
import sesIcon from '../icons/subjects/ses.png';
import siIcon from '../icons/subjects/si.png';
import st2sIcon from '../icons/subjects/st2s.png';
import std2aIcon from '../icons/subjects/std2a.png';
import sti2dIcon from '../icons/subjects/sti2d.png';
import stlIcon from '../icons/subjects/stl.png';
import stmgIcon from '../icons/subjects/stmg.png';
import svtIcon from '../icons/subjects/svt.png';
import technologieIcon from '../icons/subjects/technologie.png';

export const useJsonLevels = () => {
  const levelsData = [
    {
      value: '5ème',
      subjects: [
        {
          value: 'Histoire',
          image: histoireIcon,
          sequences: [
            "Byzance et l'Europe carolingienne",
            "L'Islam : débuts, expansion, sociétés",
            'La Méditerranée : un carrefour de civilisations',
            "L'ordre seigneurial : la formation et la domination des campagnes",
            "L'émergence d'une nouvelle société urbaine",
            "L'affirmation de l'État monarchique en France",
            "Le rôle de l'Église dans la société",
            'Le monde au temps de Charles Quint et Soliman le Magnifique',
            'Humanisme, Réformes et conflits religieux',
            'Du Prince de la Renaissance au roi absolu',
          ],
        },
        {
          value: 'SVT',
          image: svtIcon,
          sequences: [
            "Météorologie et climats : comprendre le temps qu'il fait",
            "L'eau sur Terre : un cycle et une ressource",
            'Paysages, géologie locale et action humaine',
            'Les besoins des êtres vivants : nutrition et relations',
            'Le peuplement des milieux au cours des saisons',
            'Les microbes et notre corps',
            'Devenir des aliments : la digestion',
            "L'approvisionnement des organes : respiration et circulation",
            'Le fonctionnement des organes : le besoin en énergie',
          ],
        },
        {
          value: 'Technologie',
          image: technologieIcon,
          sequences: [
            "De l'analyse du besoin aux fonctions de l'objet",
            'Imaginer et représenter des solutions techniques en équipe',
            "Anatomie d'un objet simple : comment ça marche ?",
            "L'évolution des objets et leur impact sur nos vies",
            'Identifier et choisir les matériaux',
            "Analyser la structure et les mécanismes d'un objet",
            'Atelier de Fabrication : des outils et des règles pour créer',
            'Communiquer une idée : la représentation technique',
            'Concevoir en 3D sur ordinateur (Initiation CAO)',
            'Maîtriser son environnement numérique (ENT)',
            'Premiers pas de Citoyen Numérique : se présenter et échanger en ligne',
            "Donner des ordres à l'ordinateur : l'algorithme et les blocs",
          ],
        },
      ],
    },
    {
      value: '4ème',
      subjects: [
        {
          value: 'Histoire',
          image: histoireIcon,
          sequences: [
            'Bourgeoisies marchandes, négoces internationaux et traite négrière',
            "L'Europe des Lumières",
            "La Révolution française et l'Empire",
            "L'Europe de la 'Révolution industrielle'",
            'Conquêtes et sociétés coloniales',
            'Une difficile conquête : voter de 1815 à 1870',
            'La Troisième République',
            'Conditions féminines dans une société en mutation',
          ],
        },
        {
          value: 'SVT',
          image: svtIcon,
          sequences: [
            "L'activité interne du globe : volcans et séismes",
            'La tectonique des plaques : une planète en mouvement',
            'La reproduction des êtres vivants',
            'Parentés et classification des êtres vivants',
            "La transmission de la vie chez l'Homme",
            'Maîtrise de la reproduction et sexualité',
            'Le système nerveux : perception et communication',
            'Le système nerveux : la commande du mouvement',
            'Perturbations du système nerveux',
          ],
        },
        {
          value: 'Technologie',
          image: technologieIcon,
          sequences: [
            'Le Cahier des Charges Fonctionnel (CdCF)',
            "Ergonomie et Design : l'expérience utilisateur (UX)",
            'Les Tendances du Design : pourquoi les objets ont ce look ?',
            "Analyse de système : Chaîne d'information et d'énergie",
            "Gestion de l'Énergie : comment alimenter nos objets ?",
            'Impact environnemental et Analyse du Cycle de Vie (ACV)',
            "Modélisation 3D d'un mécanisme assemblé (CAO)",
            'La simulation numérique : tester avant de construire',
            'Algorithmique : variables, conditions et boucles',
            'Enquête sur nos Données Numériques : collecte, tri et analyse',
            'Piloter un système : Capteurs, actionneurs et microcontrôleur',
            'Architecture et fonctionnement des réseaux informatiques',
          ],
        },
      ],
    },
    {
      value: '3ème',
      subjects: [
        {
          value: 'Histoire',
          image: histoireIcon,
          sequences: [
            'Civils et militaires dans la Première Guerre mondiale',
            'Démocraties fragilisées et expériences totalitaires',
            "La Seconde Guerre mondiale, une guerre d'anéantissement",
            'Indépendances et construction de nouveaux États',
            'Un monde bipolaire au temps de la guerre froide',
            'Affirmation et mise en œuvre du projet européen',
            'Enjeux et conflits dans le monde après 1989',
            'La IVe République, une république nouvelle',
            'La Ve République',
            'Femmes et hommes dans la société des années 1950 aux années 1980',
          ],
        },
        {
          value: 'SVT',
          image: svtIcon,
          sequences: [
            'Les écosystèmes et la responsabilité humaine',
            'Exploitation des ressources et grands enjeux',
            "L'information génétique : support et transmission",
            "La transmission de l'information génétique",
            'Mutations, diversité et évolution',
            "Les défenses de l'organisme : l'immunité",
            'Aider le système immunitaire : vaccination et antibiothérapie',
            'Le dialogue nerveux : neurones et synapses',
            'Le cerveau, un organe fragile et plastique',
          ],
        },
        {
          value: 'Technologie',
          image: technologieIcon,
          sequences: [
            'Conduire une démarche de projet en équipe',
            'Innover : Veille technologique et propriété intellectuelle',
            'Analyse de systèmes complexes et mécatroniques',
            'Du prototype à la série : Procédés de fabrication',
            "Éco-conception et modèle économique : le vrai coût d'un produit",
            'Optimisation et fabrication par impression 3D (FDM)',
            'La Simulation Comportementale : prédire pour mieux concevoir',
            'Du bloc au texte : Initiation à la programmation en Python',
            'Architecture des Services en Ligne : comment fonctionne une app ?',
            "Projet : Prototyper une solution avec l'Intelligence Artificielle",
            'Cybersécurité : se protéger et protéger ses données',
            "Préparer et présenter son projet pour l'oral du DNB",
          ],
        },
      ],
    },
    {
      value: 'Seconde',
      subjects: [
        {
          value: 'Enseignement moral et civique',
          image: educationMoraleCiviqueIcon,
          sequences: ['La liberté, les libertés'],
        },
        {
          value: 'Éducation physique et sportive',
          image: epsIcon,
          sequences: [
            'Réaliser une performance motrice maximale mesurable à une échéance donnée',
            'Adapter son déplacement à des environnements variés ou incertains',
            'Réaliser une prestation corporelle destinée à être vue et appréciée',
            'Conduire et maîtriser un affrontement collectif ou interindividuel pour gagner',
            "Réaliser une activité physique pour développer ses ressources et s'entretenir",
          ],
        },
        {
          value: 'Français',
          image: francaisIcon,
          sequences: [
            'La poésie du Moyen Âge au XVIIIe siècle',
            "La littérature d'idées et la presse du XIXe siècle au XXIe siècle",
            'Le roman et le récit du XVIIIe siècle au XXIe siècle',
            'Le théâtre du XVIIe siècle au XXIe siècle',
          ],
        },
        {
          value: 'Histoire-géographie',
          image: histoireGeoPolitiqueIcon,
          sequences: [
            "L'ouverture atlantique : les conséquences de la découverte du Nouveau Monde",
            "Renaissance, Humanisme et réformes religieuses : les mutations de l'Europe",
            "L'affirmation de l'État dans le royaume de France (XVIe-XVIIIe siècle)",
            'Le modèle britannique et son influence',
            'Les Lumières et le développement des sciences',
            "La Révolution française et l'Empire : une nouvelle conception de la nation",
            'Sociétés et environnements : des équilibres fragiles',
            'Territoires, populations et développement : quels défis ?',
            'Des mobilités généralisées',
            "L'Afrique australe : un espace en profonde mutation",
          ],
        },
        {
          value: 'Allemand',
          image: allemandIcon,
          sequences: [
            'Vivre entre générations',
            'Les univers professionnels, le monde du travail',
            'Le village, le quartier, la ville',
            'Représentation de soi et rapport à autrui',
            'Sports et société',
            'La création et le rapport aux arts',
            'Sauver la planète, penser les futurs possibles',
            'Le passé dans le présent',
          ],
        },
        {
          value: 'Anglais',
          image: anglaisIcon,
          sequences: [
            'Vivre entre générations',
            'Les univers professionnels, le monde du travail',
            'Le village, le quartier, la ville',
            'Représentation de soi et rapport à autrui',
            'Sports et société',
            'La création et le rapport aux arts',
            'Sauver la planète, penser les futurs possibles',
            'Le passé dans le présent',
          ],
        },
        {
          value: 'Espagnol',
          image: espagnolIcon,
          sequences: [
            'Vivre entre générations',
            'Les univers professionnels, le monde du travail',
            'Le village, le quartier, la ville',
            'Représentation de soi et rapport à autrui',
            'Sports et société',
            'La création et le rapport aux arts',
            'Sauver la planète, penser les futurs possibles',
            'Le passé dans le présent',
          ],
        },
        {
          value: 'Italien',
          image: italienIcon,
          sequences: [
            'Vivre entre générations',
            'Les univers professionnels, le monde du travail',
            'Le village, le quartier, la ville',
            'Représentation de soi et rapport à autrui',
            'Sports et société',
            'La création et le rapport aux arts',
            'Sauver la planète, penser les futurs possibles',
            'Le passé dans le présent',
          ],
        },
        {
          value: 'Mathématiques',
          image: mathematiquesIcon,
          sequences: [
            'Nombres et calculs',
            'Géométrie',
            'Fonctions',
            'Statistiques et probabilités',
            'Algorithmique et programmation',
          ],
        },
        {
          value: 'Physique-chimie',
          image: physiqueChimieIcon,
          sequences: [
            'Constitution et transformations de la matière',
            'Mouvement et interactions',
            'Ondes et signaux',
          ],
        },
        {
          value: 'Sciences de la vie et de la Terre',
          image: svtIcon,
          sequences: [
            "L'organisation fonctionnelle du vivant",
            "Biodiversité, résultat et étape de l'évolution",
            'Les enjeux contemporains de la planète : géosciences et dynamique des sols',
            'Les enjeux contemporains de la planète : agrosystèmes et développement durable',
            'Procréation et sexualité humaine',
          ],
        },
        {
          value: 'Sciences économiques et sociales',
          image: sesIcon,
          sequences: [
            'Comment les économistes, les sociologues et les politistes raisonnent-ils et travaillent-ils ?',
            'Comment crée-t-on des richesses et comment les mesure-t-on ?',
            'Comment se forment les prix sur un marché ?',
            'Comment devenons-nous des acteurs sociaux ?',
            "Comment s'organise la vie politique ?",
            "Quelles relations entre le diplôme, l'emploi et le salaire ?",
          ],
        },
        {
          value: 'Sciences numériques et technologie',
          image: genericSubjectIcon,
          sequences: [
            'Internet',
            'Le Web',
            'Les réseaux sociaux',
            'Les données structurées et leur traitement',
            'Localisation, cartographie et mobilité',
            'Informatique embarquée et objets connectés',
            'La photographie numérique',
          ],
        },
        {
          value: 'Biologie écologie',
          image: biologieEcologieIcon,
          sequences: [
            "L'organisme vivant : un système en interaction",
            'Les organismes vivants dans leur environnement',
          ],
        },
      ],
    },
    {
      value: 'Première',
      subjects: [
        {
          value: 'Enseignement moral et civique',
          image: educationMoraleCiviqueIcon,
          sequences: [
            "Comment les fondements du lien social se trouvent aujourd'hui fragilisés ?",
            'Comment les modalités de recomposition du lien social tendentelles à définir un nouveau modèle de société ?',
          ],
        },
        {
          value: 'Éducation physique et sportive',
          image: epsIcon,
          sequences: [
            'Réaliser une performance motrice maximale mesurable à une échéance donnée',
            'Adapter son déplacement à des environnements variés ou incertains',
            'Réaliser une prestation corporelle destinée à être vue et appréciée',
            'Conduire et maîtriser un affrontement collectif ou interindividuel pour gagner',
            "Réaliser une activité physique pour développer ses ressources et s'entretenir",
          ],
        },
        {
          value: 'Français',
          image: francaisIcon,
          sequences: [
            'Les subordonnées conjonctives utilisées en fonction de compléments circonstanciels',
            "L'interrogation : syntaxe, sémantique et pragmatique",
            "L'expression de la négation",
            'Lexique : néologie, relations lexicales',
            'La poésie du XIXe siècle au XXIe siècle',
            'Le roman et le récit du Moyen Âge au XXIe siècle',
            'Le théâtre du XVIIe siècle au XXIe siècle',
            "La littérature d'idées du XVIe siècle au XVIIIe siècle",
          ],
        },
        {
          value: 'Histoire-géographie',
          image: histoireGeoPolitiqueIcon,
          sequences: [
            "La Révolution française et l'Empire : une nouvelle conception de la nation",
            "L'Europe bouleversée par la Révolution française (1789-1815)",
            "L'Europe entre restauration et révolution (1814-1848)",
            'Les transformations politiques et sociales de la France de 1848 à 1870',
            "La difficile entrée dans l'âge démocratique : la Deuxième République et le Second Empire",
            "L'industrialisation et l'accélération des transformations économiques et sociales en France",
            'La France et la construction de nouveaux États par la guerre et la diplomatie',
            'La Troisième République : un régime, un empire colonial',
            'La Troisième République avant 1914 : La mise en œuvre du projet républicain',
            "La Troisième République avant 1914 : Permanences et mutations de la société française jusqu'en 1914",
            'La Troisième République avant 1914 : Métropole et colonies',
            'La Première Guerre mondiale et la fin des empires européens',
            'La Première Guerre mondiale : Un embrasement mondial et ses grandes étapes',
            'La Première Guerre mondiale : Les sociétés en guerre : des civils acteurs et victimes de la guerre',
            "La Première Guerre mondiale : Sortir de la guerre : la tentative de construction d'un ordre des nations démocratiques",
            'La métropolisation : un processus mondial différencié',
            'Une diversification des espaces et des acteurs de la production',
            'Les espaces ruraux : multifonctionnalité ou fragmentation ?',
            'La Chine : des recompositions spatiales multiples',
          ],
        },
        {
          value: 'Allemand',
          image: allemandIcon,
          sequences: [
            'Identités et échanges',
            'Espace privé et espace public',
            'Art et pouvoir',
            'Citoyenneté et mondes virtuels',
            'Fictions et réalités',
            'Innovations scientifiques et responsabilité',
            'Diversité et inclusion',
            'Territoire et mémoire',
          ],
        },
        {
          value: 'Anglais',
          image: anglaisIcon,
          sequences: [
            'Identités et échanges',
            'Espace privé et espace public',
            'Art et pouvoir',
            'Citoyenneté et mondes virtuels',
            'Fictions et réalités',
            'Innovations scientifiques et responsabilité',
            'Diversité et inclusion',
            'Territoire et mémoire',
          ],
        },
        {
          value: 'Espagnol',
          image: espagnolIcon,
          sequences: [
            'Identités et échanges',
            'Espace privé et espace public',
            'Art et pouvoir',
            'Citoyenneté et mondes virtuels',
            'Fictions et réalités',
            'Innovations scientifiques et responsabilité',
            'Diversité et inclusion',
            'Territoire et mémoire',
          ],
        },
        {
          value: 'Italien',
          image: italienIcon,
          sequences: [
            'Identités et échanges',
            'Espace privé et espace public',
            'Art et pouvoir',
            'Citoyenneté et mondes virtuels',
            'Fictions et réalités',
            'Innovations scientifiques et responsabilité',
            'Diversité et inclusion',
            'Territoire et mémoire',
          ],
        },
        {
          value: 'Mathématiques',
          image: mathematiquesIcon,
          sequences: [
            'Géométrie plane',
            "Géométrie dans l'espace",
            'Analyse : Fonctions de la variable réelle',
            'Analyse : Dérivation',
            'Statistiques et probabilités : Croisement de deux variables catégorielles',
            'Statistiques et probabilités : Probabilités conditionnelles',
            'Statistiques et probabilités : Modèle associé à une expérience aléatoire à plusieurs épreuves indépendantes',
            'Statistiques et probabilités : Variables aléatoires',
          ],
        },
        {
          value: 'Enseignement scientifique',
          image: enseignementScientifiqueIcon,
          sequences: [
            "Une longue histoire de la matière : Un niveau d'organisation, les éléments chimiques",
            'Une longue histoire de la matière : Des édifices ordonnés, les cristaux',
            'Une longue histoire de la matière : Une structure complexe, la cellule vivante',
            "Le Soleil, notre source d'énergie : Le rayonnement solaire",
            "Le Soleil, notre source d'énergie : Le bilan radiatif terrestre",
            "Le Soleil, notre source d'énergie : Une conversion biologique de l'énergie solaire : la photosynthèse",
            "Le Soleil, notre source d'énergie : Le bilan thermique du corps humain",
            'La Terre, un astre singulier : La forme de la Terre',
            "La Terre, un astre singulier : L'histoire de l'âge de la Terre",
            "La Terre, un astre singulier : La Terre dans l'Univers",
            "Son et musique, porteurs d'information : Le son, phénomène vibratoire",
            "Son et musique, porteurs d'information : La musique ou l'art de faire entendre les nombres",
            "Son et musique, porteurs d'information : Le son, une information à coder",
            "Son et musique, porteurs d'information : Entendre la musique",
          ],
        },
        {
          value: 'Sciences et technologies de la santé et du social (ST2S)',
          image: st2sIcon,
          sequences: [
            "Sciences et techniques sanitaires et sociales : Organisation et fonctionnement intégré de l'être humain",
            'Sciences et techniques sanitaires et sociales : Appareil locomoteur et motricité',
            'Sciences et techniques sanitaires et sociales : Appareil digestif et nutrition',
            'Sciences et techniques sanitaires et sociales : Appareil cardio-vasculaire et circulation sanguine',
            'Sciences et techniques sanitaires et sociales : Appareil respiratoire et échanges gazeux',
            'Biologie et physiopathologie humaines : Prévenir et sécuriser',
            'Biologie et physiopathologie humaines : Analyser et diagnostiquer',
            'Biologie et physiopathologie humaines : Faire des choix autonomes et responsables',
            'Physique-chimie pour la santé : Santé, bien-être et cohésion sociale',
            'Physique-chimie pour la santé : Protection sociale',
            "Physique-chimie pour la santé : Modes d'intervention sociale et en santé",
            'Physique-chimie pour la santé : Méthodologies appliquées au secteur sanitaire et social',
          ],
        },
        {
          value: 'Sciences et technologies de laboratoire (STL)',
          image: stlIcon,
          sequences: [
            'Biochimie-biologie : Mécanismes moléculaires et physiologiques de la nutrition',
            'Biochimie-biologie : Mécanismes physiologiques et moléculaires de la reproduction et de la transmission des caractères héréditaires',
            'Biochimie-biologie : Relations structures et propriétés des biomolécules',
            'Biochimie-biologie : Relations structures et fonctions physiologiques',
            'Biochimie-biologie : Milieu intérieur et homéostasie',
            'Biochimie-biologie : Information et communication',
            "Biotechnologies : S'initier à la recherche expérimentale et à la démarche de projet en biotechnologies",
            'Biotechnologies : Prévenir les risques au laboratoire de biotechnologies',
            'Biotechnologies : Obtenir des résultats de mesure fiables',
            'Biotechnologies : Utiliser des outils numériques en biotechnologies',
            "Biotechnologies : Observer la diversité du vivant à l'échelle microscopique",
            'Biotechnologies : Cultiver des micro-organismes',
            'Biotechnologies : Caractériser pour identifier les micro-organismes',
            'Biotechnologies : Réaliser un dénombrement de micro-organismes présents dans un produit biologique',
            'Biotechnologies : Préparer des solutions utilisables au laboratoire',
            'Biotechnologies : Détecter et caractériser les biomolécules',
            "Biotechnologies : Séparer les composants d'un mélange",
            "Biotechnologies : Déterminer la concentration d'une biomolécule dans un produit biologique",
            'Physique-chimie et mathématiques : Constitution de la matière',
            'Physique-chimie et mathématiques : Transformation chimique de la matière',
            'Physique-chimie et mathématiques : Mouvements et interactions',
            'Physique-chimie et mathématiques : Ondes et signaux',
            'Physique-chimie et mathématiques : Géométrie dans le plan',
            'Physique-chimie et mathématiques : Dérivées et Primitives',
            'Sciences physiques et chimiques en laboratoire : Chimie et développement durable, sécurité et environnement',
            'Sciences physiques et chimiques en laboratoire : Synthèses chimiques',
            'Sciences physiques et chimiques en laboratoire : Analyses physico-chimiques',
            'Sciences physiques et chimiques en laboratoire : Image, couleur et vision',
            'Sciences physiques et chimiques en laboratoire : Images photographiques',
            'Sciences physiques et chimiques en laboratoire : Appareil photographique numérique',
            "Sciences physiques et chimiques en laboratoire : Stockage et transmission d'une image numérique",
            'Sciences physiques et chimiques en laboratoire : Instruments de mesure',
            'Sciences physiques et chimiques en laboratoire : Chaîne de mesure',
            "Sciences physiques et chimiques en laboratoire : Utilisation d'une chaîne de mesure en tout ou rien",
          ],
        },
        {
          value:
            "Sciences et technologies de l'industrie et du développement durable (STI2D)",
          image: sti2dIcon,
          sequences: [
            'Physique-chimie : Mesure et incertitudes',
            "Physique-chimie : L'énergie et ses enjeux",
            'Physique-chimie : Énergie chimique',
            'Physique-chimie : Énergie électrique',
            'Physique-chimie : Énergie interne',
            'Physique-chimie : Énergie mécanique',
            'Physique-chimie : Énergie transportée par la lumière',
            'Physique-chimie : Propriétés des matériaux et organisation de la matière',
            'Physique-chimie : Combustions',
            'Physique-chimie : Oxydo-réduction, corrosion des matériaux, piles',
            "Physique-chimie : Notion d'onde",
            'Physique-chimie : Ondes sonores',
            'Physique-chimie : Ondes électromagnétiques',
            'Mathématiques : Géométrie dans le plan',
            'Mathématiques : Nombres complexes',
          ],
        },
        {
          value:
            'Sciences et technologies du management et de la gestion (STMG)',
          image: stmgIcon,
          sequences: [
            "Droit : Qu'est-ce que le droit ?",
            'Droit : Comment le droit permet-il de régler un litige ?',
            'Droit : Qui peut faire valoir ses droits ?',
            'Economie : Quelles sont les grandes questions économiques et leurs enjeux actuels ?',
            'Economie : Comment la richesse se crée-t-elle et se répartit-elle ?',
            "Economie : Comment les ménages décident-ils d'affecter leur revenu ?",
            "Economie : Quels modes de financement de l'activité économique ?",
            'Economie : Les marchés des biens et services sont-ils concurrentiels ?',
            'Management : À la rencontre du management des organisations',
            'Management : Le management stratégique : du diagnostic à la fixation des objectifs',
            'Management : Les choix stratégiques des organisations',
            "Sciences de gestion et numérique : De l'individu à l'acteur",
            'Sciences de gestion et numérique : Numérique et intelligence collective',
            'Sciences de gestion et numérique : Création de valeur et performance',
            'Sciences de gestion et numérique : Temps et risque',
          ],
        },
        {
          value: 'Histoire-géographie, géopolitique et sciences politiques',
          image: histoireGeoPolitiqueIcon,
          sequences: [
            'Comprendre un régime politique : la démocratie',
            'Analyser les dynamiques des puissances internationales',
            'Étudier les divisions politiques du monde : les frontières',
            "S'informer : un regard critique sur les sources et modes de communication",
            'Analyser les relations entre États et religions',
          ],
        },
        {
          value: 'Humanités, littérature et philosophie',
          image: humanitesIcon,
          sequences: [
            "Les pouvoirs de la parole. Période de référence : De l'Antiquité à l'Âge classique",
            'Les représentations du monde. Période de référence : Renaissance, Âge classique, Lumières',
            'La recherche de soi. Période de référence : Du romantisme au XXe siècle',
            "L'Humanité en question. Période de référence : Période contemporaine (XXe-XXIe siècles)",
          ],
        },
        {
          value: "Littérature et langues et cultures de l'Antiquité",
          image: llcaIcon,
          sequences: [
            'La cité entre réalités et utopies',
            'Justice des dieux, justice des hommes',
            'Amour, Amours',
            'Méditerranée : conflits, influences et échanges',
            'Grec : Etude de la langue',
          ],
        },
        {
          value: 'Mathématiques (Spécialité)',
          image: mathematiquesIcon,
          sequences: [
            'Algèbre : Suites numériques, modèles discrets',
            'Algèbre : Équations, fonctions polynômes du second degré',
            'Analyse : Dérivation',
            'Analyse : Variations et courbes représentatives des fonctions',
            'Analyse : Fonction exponentielle',
            'Analyse : Fonctions trigonométriques',
            'Géométrie : Calcul vectoriel et produit scalaire',
            'Géométrie : Géométrie repérée',
            'Probabilités et statistiques : Probabilités conditionnelles et indépendance',
            'Probabilités et statistiques : Variables aléatoires réelles',
            'Algorithmique et programmation : Notion de liste',
          ],
        },
        {
          value: 'Numérique et sciences informatiques',
          image: nsiIcon,
          sequences: [
            "Histoire de l'informatique : Événements clés de l'histoire de l'informatique",
            "Représentation des données : Types et valeurs de base, valeurs booléennes et exemples d'encodages (ASCII, Unicode)",
            'Représentation des données : Types construits, tableau indexé, dictionnaires de données',
            "Traitement de données en tables : Indexation de tables, recherche dans une table, tri d'une table, fusion de tables",
            "Interactions entre l'homme et la machine sur le Web : Modalités de l'interaction entre l'homme et la machine et évènements, interractions dans une page web, client-serveur et requêtes HTTP, formulaire de page web",
            "Architectures matérielles et systèmes d'exploitation : Modèle d'architecture séquentielle, Transmission de données dans un réseau, Protocoles de communication, Systèmes d'exploitation, Périphériques d'entrée et de sortie",
            'Langages et programmation : Constructions élémentaires, Diversité et unité des langages de programmation, Spécification, Jeux de tests, utilisations de bibliothèques',
            "Algorithmique : Parcours séquentiel d'un tableau, Algorithmes de tris, K plus proches voisins, Recherche dichotomique dans un tableau trié, Algorithmes gloutons",
          ],
        },
        {
          value: 'Physique-chimie',
          image: physiqueChimieIcon,
          sequences: [
            "Constitution et transformations de la matière : Suivi de l'évolution d'un système, siège d'une transformation",
            'Constitution et transformations de la matière : De la structure des entités aux propriétés physiques de la matière',
            "Constitution et transformations de la matière : Propriétés physico-chimiques, synthèses et combustions d'espèces chimiques organiques",
            'Mouvement et interactions : Interactions fondamentales et introduction à la notion de champ',
            "Mouvement et interactions : Description d'un fluide au repos",
            "Mouvement et interactions : Mouvement d'un système",
            "L'énergie : conversions et transferts : Aspects énergétiques des phénomènes électriques",
            "L'énergie : Aspects énergétiques des phénomènes mécaniques",
            'Ondes et signaux : Ondes mécaniques',
            'Ondes et signaux : La lumière : images et couleurs, modèles ondulatoire et particulaire',
          ],
        },
        {
          value: "Sciences de l'ingénieur",
          image: siIcon,
          sequences: [
            'Créer des produits innovants',
            'Analyser les produits existants pour appréhender leur complexité',
            'Modéliser les produits pour prévoir leurs performances',
            "Valider les performances d'un produit par les expérimentations et les simulations numériques",
            "S'informer, choisir, produire de l'information pour communiquer au sein d'une équipe ou avec des intervenants extérieurs",
          ],
        },
        {
          value: 'Sciences de la vie et de la Terre',
          image: svtIcon,
          sequences: [
            'Transmission, variation et expression du patrimoine génétique',
            'La dynamique interne de la Terre',
            'Écosystèmes et services environnementaux',
            'Variation génétique et santé',
            'Le fonctionnement du système immunitaire humain',
          ],
        },
        {
          value: 'Sciences économiques et sociales',
          image: sesIcon,
          sequences: [
            'Comment un marché concurrentiel fonctionne-t-il ?',
            'Comment les marchés imparfaitement concurrentiels fonctionnent-ils ?',
            'Quelles sont les principales défaillances du marché ?',
            'Comment les agents économiques se financent-ils ?',
            "Qu'est-ce que la monnaie et comment est-elle créée ?",
            'Comment la socialisation contribue-t-elle à expliquer les différences de comportement des individus ?',
            'Comment se construisent et évoluent les liens sociaux ?',
            'Quels sont les processus sociaux qui contribuent à la déviance ?',
            "Comment se forme et s'exprime l'opinion publique ?",
            'Voter : une affaire individuelle ou collective ?',
            "Comment l'assurance et la protection sociale contribuent-elles à la gestion des risques dans les sociétés développées ?",
            'Comment les entreprises sont-elles organisées et gouvernées ?',
          ],
        },
        {
          value: 'Biologie écologie',
          image: biologieEcologieIcon,
          sequences: [
            'Enjeux environnementaux : Transformation des habitats et accès aux ressources',
            'Enjeux environnementaux : Erosion de la biodiversité',
            'Enjeux de santé : Alimentation, microbiote et santé',
            'Enjeux de santé : Conduites addictives et risques pour la santé',
            'Enjeux de santé : Immunité, environnement et santé',
            'Enjeux de santé : Activité physique et santé',
            'Enjeux de santé : Génétique, environnement et santé',
          ],
        },
      ],
    },
    {
      value: 'Terminale',
      subjects: [
        {
          value: 'Éducation physique et sportive',
          image: epsIcon,
          sequences: [
            'Réaliser une performance motrice maximale mesurable à une échéance donnée',
            'Adapter son déplacement à des environnements variés ou incertains',
            'Réaliser une prestation corporelle destinée à être vue et appréciée',
            'Conduire et maîtriser un affrontement collectif ou interindividuel pour gagner',
            "Réaliser une activité physique pour développer ses ressources et s'entretenir",
          ],
        },
        {
          value:
            'Sciences et technologies du design et des arts appliqués (STD2A)',
          image: std2aIcon,
          sequences: [
            "Design et métiers d'art : La place du dessin",
            "Design et métiers d'art : La place des outils numériques",
            "Design et métiers d'art : L'observation du présent comme tremplin à l'innovation",
          ],
        },
        {
          value:
            "Sciences et technologies de l'industrie et du développement durable (STI2D)",
          image: sti2dIcon,
          sequences: [
            'Innovation technologique :',
            'Innovation technologique :',
            'Ingénierie et développement durable :',
            'Ingénierie et développement durable :',
          ],
        },
        {
          value:
            'Sciences et technologies du management et de la gestion (STMG)',
          image: stmgIcon,
          sequences: [
            'Management : À la rencontre du management des organisations',
            'Management : Le management stratégique : du diagnostic à la fixation des objectifs',
            'Management : Les choix stratégiques des organisations',
            "Sciences de gestion et numérique : De l'individu à l'acteur",
            'Sciences de gestion et numérique : Numérique et intelligence collective',
            'Sciences de gestion et numérique : Création de valeur et performance',
            'Sciences de gestion et numérique : Temps et risque',
          ],
        },
        {
          value: 'Histoire-géographie, géopolitique et sciences politiques',
          image: histoireGeoPolitiqueIcon,
          sequences: [
            'Comprendre un régime politique : la démocratie',
            'Analyser les dynamiques des puissances internationales',
            'Étudier les divisions politiques du monde : les frontières',
            "S'informer : un regard critique sur les sources et modes de",
            'communication',
            'Analyser les relations entre États et religions',
          ],
        },
        {
          value: 'Humanités, littérature et philosophie',
          image: humanitesIcon,
          sequences: [
            "Les pouvoirs de la parole. Période de référence : De l'Antiquité à l'Âge classique",
            'Les représentations du monde. Période de référence : Renaissance, Âge classique, Lumières',
            'La recherche de soi. Période de référence : Du romantisme au XXe siècle',
            "L'Humanité en question. Période de référence : Période contemporaine (XXe-XXIe siècles)",
          ],
        },
        {
          value: "Littérature et langues et cultures de l'Antiquité",
          image: llcaIcon,
          sequences: [
            'La cité entre réalités et utopies',
            'Justice des dieux, justice des hommes',
            'Amour, Amours',
            'Méditerranée : conflits, influences et échanges',
            'Grec : Etude de la langue',
          ],
        },
        {
          value: 'Mathématiques',
          image: mathematiquesIcon,
          sequences: [
            'Algèbre : Suites numériques, modèles discrets',
            'Algèbre : Équations, fonctions polynômes du second degré',
            'Analyse : Dérivation',
            'Analyse : Variations et courbes représentatives des fonctions',
            'Analyse : Fonction exponentielle',
            'Analyse : Fonctions trigonométriques',
            'Géométrie : Calcul vectoriel et produit scalaire',
            'Géométrie : Géométrie repérée',
            'Probabilités et statistiques : Probabilités conditionnelles et indépendance',
            'Probabilités et statistiques : Variables aléatoires réelles',
            'Algorithmique et programmation : Notion de liste',
          ],
        },
        {
          value: 'Numérique et sciences informatiques',
          image: nsiIcon,
          sequences: [
            "Histoire de l'informatique : Événements clés de l'histoire de l'informatique",
            "Représentation des données : Types et valeurs de base, valeurs booléennes et exemples d'encodages (ASCII, Unicode)",
            'Représentation des données : Types construits, tableau indexé, dictionnaires de données',
            "Traitement de données en tables : Indexation de tables, recherche dans une table, tri d'une table, fusion de tables",
            "Interactions entre l'homme et la machine sur le Web : Modalités de l'interaction entre l'homme et la machine et évènements, interractions dans une page web, client-serveur et requêtes HTTP, formulaire de page web",
            "Architectures matérielles et systèmes d'exploitation : Modèle d'architecture séquentielle, Transmission de données dans un réseau, Protocoles de communication, Systèmes d'exploitation, Périphériques d'entrée et de sortie",
            'Langages et programmation : Constructions élémentaires, Diversité et unité des langages de programmation, Spécification, Jeux de tests, utilisations de bibliothèques',
            "Algorithmique : Parcours séquentiel d'un tableau, Algorithmes de tris,  K plus proches voisins, Recherche dichotomique dans un tableau trié, Algorithmes gloutons",
          ],
        },
        {
          value: 'Physique-chimie',
          image: physiqueChimieIcon,
          sequences: [
            "Constitution et transformations de la matière : Déterminer la composition d'un système par des méthodes physiques et chimiques",
            "Constitution et transformations de la matière : Modéliser l'évolution temporelle d'un système, siège d'une transformation",
            "Constitution et transformations de la matière : Prévoir l'état final d'un système, siège d'une transformation chimique",
            'Constitution et transformations de la matière : Élaborer des stratégies en synthèse organique',
            "Mouvement et interactions : Décrire un mouvement (Vecteurs position, vitesse et accélération d'un point, accélération dans le repère de Frenet, Mouvement rectiligne uniformément accéléré et circulaire uniforme)",
            'Mouvement et interactions : Relier les actions appliquées à un système à son mouvement (Deuxième loi de Newton, Mouvement dans un champ uniforme, Mouvement dans un champ de gravitation)',
            "Mouvement et interactions : Modéliser l'écoulement d'un fluide (Poussée d'Archimède, Écoulement d'un fluide en régime permanent, Débit volumique d'un fluide incompressible, Relation de Bernoulli, Effet Venturi)",
            "L'énergie - conversions et transferts :  Décrire un système thermodynamique : exemple du modèle du gaz parfait",
            "L'énergie - conversions et transferts : Effectuer des bilans d'énergie sur un système : le premier principe de la thermodynamique (Capacité thermique et énergie interne d'un système incompressible, transferts et flux, Loi phénoménologique de Newton, modélisation de l'évolution de la température d'un système au contact d'un thermostat)",
            "Ondes et signaux : Caractériser les phénomènes ondulatoires (Intensité sonore, Diffraction, Interférences de deux ondes, conditions d'observation. Interférences constructives, Interférences destructives (lumineuses), Effet Doppler et Décalage Doppler)",
            'Ondes et signaux : Former des images, décrire la lumière par un flux de photons (Former des images, Décrire la lumière par un flux de photons)',
            "Ondes et signaux : Étudier la dynamique d'un système électrique (Comportement capacitif, Modèle du condensateur, Relation entre charge et tension et capacité d'un condensateur)",
          ],
        },
        {
          value: "Sciences de l'ingénieur",
          image: siIcon,
          sequences: [
            'Créer des produits innovants',
            'Analyser les produits existants pour appréhender leur complexité',
            'Modéliser les produits pour prévoir leurs performances',
            "Valider les performances d'un produit par les expérimentations et les simulations numériques",
            "S'informer, choisir, produire de l'information pour communiquer au sein d'une équipe ou avec des intervenants extérieurs",
          ],
        },
        {
          value: 'Sciences de la vie et de la Terre',
          image: svtIcon,
          sequences: [
            "La Terre, la vie et l'organisation du vivant : Les divisions cellulaires des eucaryotes",
            "La Terre, la vie et l'organisation du vivant : La réplication de l'ADN",
            "La Terre, la vie et l'organisation du vivant : Mutations de l'ADN et variabilité génétique",
            "La Terre, la vie et l'organisation du vivant : L'histoire humaine lue dans son génome",
            "La Terre, la vie et l'organisation du vivant : L'expression du patrimoine génétique",
            "La Terre, la vie et l'organisation du vivant : Les enzymes, des biomolécules aux propriétés catalytiques",
            'La dynamique interne de la Terre : La structure du globe terrestre',
            'La dynamique interne de la Terre : La dynamique de la lithosphère',
            'Les écosystèmes : des interactions dynamiques entre les êtres vivants et entre eux et leur milieu',
            "L'humanité et les écosystèmes : les services écosystémiques et leur gestion",
            'Variation génétique et santé : Mutations et santé',
            'Variation génétique et santé : Patrimoine génétique et santé',
            'Variation génétique et santé : Altérations du génome et cancérisation',
            'Variation génétique et santé : Variation génétique bactérienne et résistance aux antibiotiques',
            "Le fonctionnement du système immunitaire humain : L'immunité innée",
            "Le fonctionnement du système immunitaire humain : L'immunité adaptative",
            "Le fonctionnement du système immunitaire humain : L'utilisation de l'immunité adaptative en santé humaine",
          ],
        },
        {
          value: 'Sciences économiques et sociales',
          image: sesIcon,
          sequences: [
            'Comment un marché concurrentiel fonctionne-t-il ?',
            'Comment les marchés imparfaitement concurrentiels fonctionnent-ils ?',
            'Quelles sont les principales défaillances du marché ?',
            'Comment les agents économiques se financent-ils ?',
            "Qu'est-ce que la monnaie et comment est-elle créée ?",
            'Comment la socialisation contribue-t-elle à expliquer les différences de comportement des individus ?',
            'Comment se construisent et évoluent les liens sociaux ?',
            'Quels sont les processus sociaux qui contribuent à la déviance ?',
            "Comment se forme et s'exprime l'opinion publique ?",
            'Voter : une affaire individuelle ou collective ?',
            "Comment l'assurance et la protection sociale contribuent-elles à la gestion des risques dans les sociétés développées ?",
            'Comment les entreprises sont-elles organisées et gouvernées ?',
          ],
        },
        {
          value: 'Arts',
          image: artsPlastiquesIcon,
          sequences: [
            'La représentation, ses langages, moyens plastiques et enjeux artistiques',
            "La figuration et l'image, la non-figuration",
            "La matière, les matériaux et la matérialité de l'œuvre",
            "La présentation de l'œuvre",
            "La monstration et la diffusion de l'œuvre, les lieux, les espaces, les contextes",
            "La réception par un public de l'œuvre exposée, diffusée ou éditée",
            "L'idée, la réalisation et le travail de l'œuvre",
            'Créer à plusieurs plutôt que seul',
            "Liens entre arts plastiques et architecture, paysage, design d'espace et d'objet",
            'Liens entre arts plastiques et cinéma, animation, image de synthèse, jeu vidéo',
            'Liens entre arts plastiques et théâtre, danse, musique',
            "L'artiste et la société : faire œuvre face à l'histoire et à la politique",
            "L'art, les sciences et les technologies : dialogue ou hybridation",
            'Mondialisation de la création artistique : métissages ou relativité des cultures du monde',
          ],
        },
        {
          value: 'Allemand',
          image: allemandIcon,
          sequences: [
            'Identités et échanges',
            'Espace privé et espace public',
            'Art et pouvoir',
            'Citoyenneté et mondes virtuels',
            'Fictions et réalités',
            'Innovations scientifiques et responsabilité',
            'Diversité et inclusion',
            'Territoire et mémoire',
          ],
        },
        {
          value: 'Anglais',
          image: anglaisIcon,
          sequences: [
            'Identités et échanges',
            'Espace privé et espace public',
            'Art et pouvoir',
            'Citoyenneté et mondes virtuels',
            'Fictions et réalités',
            'Innovations scientifiques et responsabilité',
            'Diversité et inclusion',
            'Territoire et mémoire',
          ],
        },
        {
          value: 'Espagnol',
          image: espagnolIcon,
          sequences: [
            'Identités et échanges',
            'Espace privé et espace public',
            'Art et pouvoir',
            'Citoyenneté et mondes virtuels',
            'Fictions et réalités',
            'Innovations scientifiques et responsabilité',
            'Diversité et inclusion',
            'Territoire et mémoire',
          ],
        },
        {
          value: 'Italien',
          image: italienIcon,
          sequences: [
            'Identités et échanges',
            'Espace privé et espace public',
            'Art et pouvoir',
            'Citoyenneté et mondes virtuels',
            'Fictions et réalités',
            'Innovations scientifiques et responsabilité',
            'Diversité et inclusion',
            'Territoire et mémoire',
          ],
        },
        {
          value: 'Biologie écologie',
          image: biologieEcologieIcon,
          sequences: [
            'Enjeux environnementaux : Transformation des habitats et accès aux ressources',
            'Enjeux environnementaux : Erosion de la biodiversité',
            'Enjeux de santé : Alimentation, microbiote et santé',
            'Enjeux de santé : Conduites addictives et risques pour la santé',
            'Enjeux de santé : Immunité, environnement et santé',
            'Enjeux de santé : Activité physique et santé',
            'Enjeux de santé : Génétique, environnement et santé',
          ],
        },
      ],
    },
  ];

  return {
    levelsData,
  };
};
