name: tests

on:
  push:
    branches:
      - main
      - develop
      - develop*
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Generate .npmrc
        run: |
          pnpm config set @tiptap-pro:registry https://registry.tiptap.dev
          pnpm config set //registry.tiptap.dev/:_authToken ${{ secrets.TIPTAP_PRO_TOKEN }}
          pnpm config set auto-install-peers true
      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm exec nx test

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# jobs:
#   tests:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: "0"

#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - uses: pnpm/action-setup@v4
#         id: pnpm-install
#         with:
#           version: 9.4.0
#           run_install: false
#         env:
#           TIPTAP_PRO_TOKEN: ${{ secrets.TIPTAP_PRO_TOKEN }}

#       - name: Generate .npmrc
#         run: |
#           pnpm config set @tiptap-pro:registry https://registry.tiptap.dev
#           pnpm config set //registry.tiptap.dev/:_authToken ${{ secrets.TIPTAP_PRO_TOKEN }}
#           pnpm config set auto-install-peers true

#       - run: pnpm install --frozen-lockfile
#       - run: pnpm exec nx test

#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
